project:
  type: website

website:
  title: "Patrick Bernhard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Bernhard_Patrick_CV.pdf
        text: CV

format:
  html:
    theme: 
    - cosmo
    - syles.scss
    css: styles.css
    toc: true



